//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyRecruit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Headstep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Headstep()
        {
            this.Substeps = new HashSet<Substep>();
            this.HeadStats = new HashSet<HeadStat>();
        }
    
        public int HeadstepID { get; set; }
        public decimal Number { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IsDone { get; set; }
        public string Notes { get; set; }
        public decimal Points { get; set; }
        public int MainstepID { get; set; }
    
        public virtual Mainstep Mainstep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Substep> Substeps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeadStat> HeadStats { get; set; }
    }
}
