//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyRecruit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int LinkID { get; set; }
        public int ProfileID { get; set; }
        public int RoadmapID { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Roadmap Roadmap { get; set; }
    }
}
