//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyRecruit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.Links = new HashSet<Link>();
        }
    
        public int ProfileID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public int Dependents { get; set; }
        public string Title { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> AsvabScore { get; set; }
        public Nullable<decimal> PracticeScore { get; set; }
        public Nullable<decimal> PointsTotal { get; set; }
        public Nullable<decimal> PointsEarned { get; set; }
        public bool IsDone { get; set; }
        public int GenderID { get; set; }
        public int EducationID { get; set; }
        public int MaritalStatID { get; set; }
        public int PriorServiceID { get; set; }
        public string Id { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link> Links { get; set; }
        public virtual MaritalStat MaritalStat { get; set; }
        public virtual PriorService PriorService { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
