//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyRecruit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReadyRecruitEntities : DbContext
    {
        public ReadyRecruitEntities()
            : base("name=ReadyRecruitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Headstep> Headsteps { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Mainstep> Mainsteps { get; set; }
        public virtual DbSet<MaritalStat> MaritalStats { get; set; }
        public virtual DbSet<PriorService> PriorServices { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Roadmap> Roadmaps { get; set; }
        public virtual DbSet<Substep> Substeps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
