//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyRecruit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Substep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Substep()
        {
            this.SubStats = new HashSet<SubStat>();
        }
    
        public int SubstepID { get; set; }

        [Required]
        public decimal Number { get; set; }

        [Required]
        public string Name { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DueDate { get; set; }

        [Required, Display(Name = "Finished?")]
        public bool IsDone { get; set; }

        public string Notes { get; set; }

        [Required]
        public decimal Points { get; set; }
        public int HeadstepID { get; set; }
    
        public virtual Headstep Headstep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubStat> SubStats { get; set; }
    }
}
